### ISSUE TITLE
Error While starting web application

### ISSUE THREAD

**Issue by vikas1539** [Morningstar/kafka-offset-monitor#13]
Getting following exception while starting the app. Please let me know solution. I have try to build project by checkout fresh code but got same exception while building during test execution.
```
sangal@visangal-consumer:~/offsetMonitor/kafka-offset-monitor/target/scala-2.11$ java -Djava.security.auth.login.config=conf/server-client-jaas.conf -cp KafkaOffsetMonitor-assembly-0.4.1-SNAPSHOT.jar com.quantifind.kafka.offsetapp.OffsetGetterWeb --offsetStorage kafka  --kafkaBrokers localhost:9092,localhost:9093,localhost:9094,localhost:9094  --zk localhost:8081 --port 8087 --refresh 10.seconds   --retain 2.days --dbName offsetapp_kafka
serving resources from: jar:file:/mnt/svmdev01expodevusers/sangal/offsetMonitor/kafka-offset-monitor/target/scala-2.11/KafkaOffsetMonitor-assembly-0.4.1-SNAPSHOT.jar!/offsetapp
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twitter/util/Time : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$TimeSerializer.<init>(OffsetGetterWeb.scala:126)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1.<init>(OffsetGetterWeb.scala:138)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:137)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:46)
        at com.quantifind.utils.UnfilteredWebApp$class.main(UnfilteredWebApp.scala:29)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
        at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
        at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
        at com.quantifind.kafka.offsetapp.OffsetGetterWeb.main(OffsetGetterWeb.scala)

```

**Comment by vikas1539** [comment]
Able to find root cause. We need to start our app with jdk version 8 and above.
