### ISSUE TITLE
KafkaOffsetGetter Unhandled NullPointerException

### ISSUE THREAD

**Issue by kiritisai** [Morningstar/kafka-offset-monitor#2]
I'm using Kafka v.0.10.1 and I have 3 brokers running in my local system at different ports. I face the following exception when I've tried to use the 0.4.1-SNAPSHOT.jar file.
```
2017-04-05 10:50:50 INFO  KafkaOffsetGetter$:236 - Creating new Kafka Client to get consumer group committed offsets
2017-04-05 10:50:50 ERROR KafkaOffsetGetter$:103 - The Kafka Client reading topic/partition LogEndOffsets has thrown an unhandled exception.  Will attempt to reconnect.
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.createNewKafkaConsumer(KafkaOffsetGetter.scala:115)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.startLogEndOffsetGetter(KafkaOffsetGetter.scala:418)
        at com.quantifind.kafka.OffsetGetter$$anon$2.run(OffsetGetter.scala:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-05 10:50:50 ERROR KafkaOffsetGetter$:103 - The Kafka Client reading topic/partition LogEndOffsets has thrown an unhandled exception.  Will attempt to reconnect.
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.createNewKafkaConsumer(KafkaOffsetGetter.scala:115)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.startLogEndOffsetGetter(KafkaOffsetGetter.scala:418)
        at com.quantifind.kafka.OffsetGetter$$anon$2.run(OffsetGetter.scala:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-05 10:50:50 ERROR KafkaOffsetGetter$:103 - The Kafka Client reading topic/partition LogEndOffsets has thrown an unhandled exception.  Will attempt to reconnect.
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.createNewKafkaConsumer(KafkaOffsetGetter.scala:115)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.startLogEndOffsetGetter(KafkaOffsetGetter.scala:418)
        at com.quantifind.kafka.OffsetGetter$$anon$2.run(OffsetGetter.scala:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-05 10:50:50 ERROR KafkaOffsetGetter$:103 - An unhandled exception was thrown while reading messages from the committed offsets topic.
```
The command I've used for running the jar is 
`java -cp KafkaOffsetMonitor-assembly-0.4.1-SNAPSHOT.jar com.quantifind.kafka.offsetapp.OffsetGetterWeb --offsetStorage kafka --zk localhost --port 8000 --refresh 10.seconds --retain 2.days`

**Comment by rcasey212** [comment]
I believe you are missing the "--kafkaBrokers" param on the command-line when starting.  Try fixing that and see if it helps.
