### ISSUE TITLE
file missing conf/server-client-jaas.confcannot be read.

### ISSUE THREAD

**Issue by Laxman-SM** [Morningstar/kafka-offset-monitor#27]
I am getting this error during the command execution.

2018-03-28 14:58:28 INFO  OffsetGetter$:68 - Creating new ZkUtils object.
2018-03-28 14:58:28 ERROR OffsetGetter$:103 - Error creating ZkUtils.  Will attempt to re-create in 30000 seconds
org.apache.kafka.common.KafkaException: File conf/server-client-jaas.confcannot be read.
	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:95)
	at com.quantifind.kafka.OffsetGetter$.createZkUtils(OffsetGetter.scala:246)
	at com.quantifind.kafka.OffsetGetter$.getInstance(OffsetGetter.scala:273)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.reportOffsets(OffsetGetterWeb.scala:74)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anonfun$schedule$1.apply$mcV$sp(OffsetGetterWeb.scala:99)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$2.run(OffsetGetterWeb.scala:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**org.apache.kafka.common.KafkaException: File conf/server-client-jaas.confcannot be read.**

where this files are defined. unable to get the file location. even compiled version i am getting same error. thanks in advance.

**Comment by rcasey212** [comment]
Hi @Laxman-SM,

It appears you forgot to pass the location to your jaas.conf file at the start of the application.  See this closed issue for more information: https://github.com/Morningstar/kafka-offset-monitor/issues/6

**Comment by yluom** [comment]
If you don't need authentication, just remove the -Djava.security.auth.login.config option.
