### ISSUE TITLE
You must pass java.security.auth.login.config in secure mode

### ISSUE THREAD

**Issue by mrzhangxing** [Morningstar/kafka-offset-monitor#6]
Ask for help
version:
kafka_2.10-0.10.2.0
KafkaOffsetMonitor-assembly-0.4.1-SNAPSHOT.jar

log:
2017-05-18 11:30:10 ERROR KafkaOffsetGetter$:103 - Error creating an AdminClient.  Will attempt to re-create in 60000 seconds
org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79)
        at kafka.admin.AdminClient$.create(AdminClient.scala:217)
        at kafka.admin.AdminClient$.create(AdminClient.scala:211)
        at kafka.admin.AdminClient$.create(AdminClient.scala:209)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.com$quantifind$kafka$core$KafkaOffsetGetter$$createNewAdminClient(KafkaOffsetGetter.scala:130)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startAdminClient$1.apply$mcV$sp(KafkaOffsetGetter.scala:228)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startAdminClient$1.apply(KafkaOffsetGetter.scala:222)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startAdminClient$1.apply(KafkaOffsetGetter.scala:222)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.security.kerberos.Login.login(Login.java:289)
        at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104)
        at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44)
        at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55)
        ... 16 more
2017-05-18 11:30:10 FATAL KafkaOffsetGetter$:116 - The Kafka Client reading topic/partition LogEndOffsets has thrown an unhandled exception.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:648)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.com$quantifind$kafka$core$KafkaOffsetGetter$$createNewKafkaConsumer(KafkaOffsetGetter.scala:112)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startTopicPartitionOffsetGetter$1.apply$mcV$sp(KafkaOffsetGetter.scala:319)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startTopicPartitionOffsetGetter$1.apply(KafkaOffsetGetter.scala:309)
        at com.quantifind.kafka.core.KafkaOffsetGetter$$anonfun$startTopicPartitionOffsetGetter$1.apply(KafkaOffsetGetter.scala:309)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:577)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
        at org.apache.kafka.common.security.kerberos.Login.login(Login.java:289)
        at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104)
        at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44)
        at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85)
        at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55)
        ... 16 more
2017-05-18 11:30:10 INFO  ContextHandler:843 - stopped o.e.j.s.ServletContextHandler{/,jar:file:/opt/soft/KafkaOffsetMonitor/KafkaOffsetMonitor-assembly-0.4.0-SNAPSHOT.jar!/offsetapp}

**Comment by rcasey212** [comment]
Hi @mrzhangxing, it looks to me like you forgot to pass your jaas.conf file on the command-line when starting with the -D option: ```-Djava.security.auth.login.config=```

**Comment by mrzhangxing** [comment]
thank you
