### ISSUE TITLE
Not able to use with kafka 0.10.2

### ISSUE THREAD

**Issue by ronakkothari** [Morningstar/kafka-offset-monitor#9]
We are using the version of kafka 0.10.2 and would like to use this tool. I have tried the command mentioned in wiki after downloading the latest release,

java -Djava.security.auth.login.config=conf/server-client-jaas.conf \
	-cp KafkaOffsetMonitor-assembly-0.4.1.jar \
       com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --offsetStorage kafka \
     --kafkaBrokers kafkabroker01:6667,kafkabroker02:6667 \
     --zk zkserver01,zkserver02 \
     --port 8081 \
     --refresh 10.seconds \
     --retain 2.days \
     --dbName offsetapp_kafka

However, it doesn't show any data. Does this tool work with 0.10.2?

**Comment by Rohlik** [comment]
We using this tool with Kafka version 0.10.2.1 and we can see data on the web page.

**Comment by ronakkothari** [comment]
Hello Rohlik, have you made any specific changes as I could see in build.sbt the kafka version is ' "org.apache.kafka" %% "kafka" % "0.9.0.1" '. Have you guys made any specific changes?

**Comment by ronakkothari** [comment]
I think, I got the answer, this fork - https://github.com/kadaan/kafka-offset-monitor - works.

**Comment by Rohlik** [comment]
I using this parameters:
```
java -Xmx512m -cp KafkaOffsetMonitor-assembly-0.4.1-SNAPSHOT.jar \
     com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --zk $ZK01,$ZK02,$ZK03 \
     --port $PORT \
     --refresh $REFRESH \
     --retain $RETAIN >> $LOG_DIR/$LOG_FILE 2>&1 &
```

**Comment by ybyd2005** [comment]
I using this parameters:

`java -cp KafkaOffsetMonitor-assembly-0.4.0.jar \
       com.quantifind.kafka.offsetapp.OffsetGetterWeb \
     --zk 172.19.6.222 \
     --port 2288 \
     --refresh 10.seconds \
     --retain 2.days \
     --dbName offsetapp_kafka
`

But when I started, there was a problem：

`serving resources from: jar:file:/root/KafkaOffsetMonitor-assembly-0.4.0.jar!/offsetapp
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twitter/util/Time : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$TimeSerializer.<init>(OffsetGetterWeb.scala:126)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1.<init>(OffsetGetterWeb.scala:138)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:137)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:46)
	at com.quantifind.utils.UnfilteredWebApp$class.main(UnfilteredWebApp.scala:29)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
	at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45)
	at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46)
	at com.quantifind.kafka.offsetapp.OffsetGetterWeb.main(OffsetGetterWeb.scala)
`
